### ISSUE TITLE
Kelp/Seagrass texture broken - Faithful x64

### ISSUE THREAD

**Issue by omega9380** [Faithful-Resource-Pack/Faithful-Java-64x#10] opened 2022-08-05 12:00 UTC
The kelp and seagrass textures appear to be broken in Faithful x64.  I'm running x64 from the latest Gitub pull as of 5 Aug at 0730 ET.

If you are wondering why I'm still running 1.19, I'm waiting for OptiFabric to be updated 😄 

Some screenies:

Running MC 1.19, Fabric 0.14.8, FabricAPI 0.57.0, OptiFabric 0.13.8, Optifine 1.19 HD U H8.  Resource pack order is Faithful 32x, Faithful 64x, Lower Fire, Visual Maps, then my own custom resource pack:
![MC 1 19 - Fabric 0 14 8 - FabricAPI 0 57 0 -  OptiFabric 0 13 8 - Faithful 32 then 64 then others - see post ](https://user-images.githubusercontent.com/13081643/183072319-cbd4ea63-cbc9-42a4-9730-488297458294.jpg)

Same location, different mods.  Running MC 1.19, Optifine 1.19 HD U H9, only Faithful x32 then x64:
![MC 1 19 - OptiFine H9 - Faithful 32 then 64](https://user-images.githubusercontent.com/13081643/183072663-2ab7576a-5db7-4c2c-8c5e-2ea23b24864f.jpg)

Same location and mods as above, except only loading Faithful x64:
![MC 1 19 - Optifine H9 - Faithful 64](https://user-images.githubusercontent.com/13081643/183072745-bda3ab41-de97-4539-a5f0-35fe0d255098.jpg)

Pure vanilla MC 1.19 with Faithful x32 then x64:
![MC 1 19 Vanilla - Faithful 32 then 64](https://user-images.githubusercontent.com/13081643/183072804-2e3a85bf-a54a-4a22-9513-c9a86730d06e.jpg)

Pure vanilla MC 1.19, just Faithful x64:
![MC 1 19 Vanilla - Faithful 64](https://user-images.githubusercontent.com/13081643/183072870-cf41baca-7eb4-4fa9-ba2d-ebc13eba0bab.jpg)

Finally, the F3 screen with all mods/resource packs loaded that I normally play MC with:
![All Mods F3](https://user-images.githubusercontent.com/13081643/183072935-886a445f-9507-4646-8912-096308de9b1d.jpg)

Hope this is enough info to fix, sorry if it's too much!  Keep up the great work folks!

**Comment by HaragOnMC** [comment] 2022-08-05 12:23
Hey! Thank you very much for your report. I am sorry this is happening ;(
I will quickly push a fix on Github.

**Comment by Juknum** [comment] 2022-08-05 12:23
@HaragOnMC it seems that `.mcmeta` files are missing

@omega9380 can you unzip the Faithful 64x version you're using & check if `.mcmeta` files are next to the kelp textures? (it's under `/assets/textures/blocks/`

**Comment by HaragOnMC** [comment] 2022-08-05 12:24
Yes, mcmeta files are missing and I'm adding them right now!

**Comment by HaragOnMC** [comment] 2022-08-05 12:29
The issue is now fixed. Please redownload the pack

**Comment by HaragOnMC** [comment] 2022-08-05 12:30
Let me know if the bug is fixed. If that's the case, I will close the ticket.

**Comment by omega9380** [comment] 2022-08-05 15:14
FIxed!  Thanks guys!
![2022-08-05_11 14 10](https://user-images.githubusercontent.com/13081643/183107543-401e7315-57cf-414f-a36b-b40d73572387.png)

**Closed** 2022-08-05 15:23 UTC
Labels: bug

**Comment by broes5** [comment] 2022-08-19 04:12
I've just noticed this issue with a version of this texture pack for Minecraft 1.16.5.
